### ISSUE TITLE
Example does not work when verify.

### ISSUE THREAD

**Issue by onishi0105** [ziima/python-openid#28]
I tried example. However,  in step 5 when I enter the URL and click on verify, the domain becomes my PC name and the screen is not displayed.
```
This site can’t be reached
desktop-xxxx refused to connect.
Search Google for desktop xxxx 8001 verify
ERR_CONNECTION_REFUSED
```
I changed the part of my PC name to localhost and reloaded, the error screen remained displayed.
http://localhost:8001/verify?openid_identifier=http%3A%2F%2Flocalhost%3A8000%2Fid%2Fbob
```
 Traceback (most recent call last):
   File "consumer.py", line 146, in do_GET
   self.doVerify()
   File "consumer.py", line 179, in doVerify
   request = oidconsumer.begin(openid_url)
   File "C:\Python27\lib\site-packages\openid\consumer\consumer.py", line 347, in begin
   raise DiscoveryFailure('Error fetching XRDS document: %s' % six.text_type(why), None)
   UnicodeDecodeError: 'ascii' codec can't decode byte 0x91 in position 29: ordinal not in range(128)
```
The environment is windows 10, python 2.7, python-openid == 3.0.

**Comment by ziima** [comment]
Hi, thanks for the report, sorry it took so long. I wasn't able to reproduce the bug, but I made some fixes in the examples.

**Comment by ziima** [comment]
Have you used `consumer` or djopenid example?
